MOCK_DATA = [
    {
        "symbol": "GE",
        "companyName": "General Electric Company",
        "exchange": "New York Stock Exchange",
        "industry": "Industrial Products",
        "website": "http://www.ge.com",
        "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
        "CEO": "John L. Flannery",
        "issueType": "cs",
        "sector": "Industrials"
    },
    {"symbol":"AAPL","companyName":"Apple Inc.","exchange":"Nasdaq Global Select","industry":"Computer Hardware","website":"http://www.apple.com","description":"Apple Inc is designs, manufactures and markets mobile communication and media devices and personal computers, and sells a variety of related software, services, accessories, networking solutions and third-party digital content and applications.","CEO":"Timothy D. Cook","issueType":"cs","sector":"Technology"},
    {"symbol":"MSFT","companyName":"Microsoft Corporation","exchange":"Nasdaq Global Select","industry":"Application Software","website":"http://www.microsoft.com","description":"Microsoft Corp is a technology company. It develop, license, and support a wide range of software products and services. Its business is organized into three segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing.","CEO":"Satya Nadella","issueType":"cs","sector":"Technology"},
    {"symbol":"GOOG","companyName":"Alphabet Inc.","exchange":"Nasdaq Global Select","industry":"Online Media","website":"https://www.abc.xyz","description":"Alphabet Inc is a provider of internet content products and portals. Its suite of brands includes Search, Android, YouTube, Apps, Maps & Ads.","CEO":"Larry Page","issueType":"cs","sector":"Technology"},
    {"symbol":"TSLA","companyName":"Tesla Inc.","exchange":"Nasdaq Global Select","industry":"Autos","website":"https://www.tesla.com","description":"Tesla Inc is a vertically integrated sustainable energy company. It designs, develops, manufactures and sells high-performance fully electric vehicles and electric vehicle powertrain components.","CEO":"Elon Musk","issueType":"cs","sector":"Consumer Cyclical"},
    {"symbol":"IBM","companyName":"International Business Machines Corporation","exchange":"New York Stock Exchange","industry":"Application Software","website":"http://www.ibm.com","description":"International Business Machines Corp offers a variety of IT services along with software, and hardware. It has operations in over 170 countries and provides planning, build, manage, and maintain IT infrastructure, platforms, applications, and services.","CEO":"Virginia M. Rometty","issueType":"cs","sector":"Technology"},
    {"symbol":"AMZN","companyName":"Amazon.com Inc.","exchange":"Nasdaq Global Select","industry":"Retail - Apparel & Specialty","website":"http://www.amazon.com","description":"Amazon.com Inc is an online retailer. The Company sells its products through the website which provides services, such as advertising services and co-branded credit card agreements. It also offers electronic devices like Kindle e-readers and Fire tablets.","CEO":"Jeffrey P. Bezos","issueType":"cs","sector":"Consumer Cyclical"},
    {"symbol":"JNPR","companyName":"Juniper Networks Inc.","exchange":"New York Stock Exchange","industry":"Communication Equipment","website":"http://www.juniper.net","description":"Juniper Networks Inc operates in the communication equipment industry. It designs, develops and sells products and services that provide customers with network infrastructure. It caters to communication service providers and companies.","CEO":"Rami Rahim","issueType":"cs","sector":"Technology"},
    {"symbol":"CSCO","companyName":"Cisco Systems Inc.","exchange":"Nasdaq Global Select","industry":"Communication Equipment","website":"http://www.cisco.com","description":"Cisco Systems Inc is a supplier of data networking equipment and software. Its products include routers, switches, access equipment, and security and network management software which allow data communication among dispersed computer networks.","CEO":"Charles Robbins","issueType":"cs","sector":"Technology"},
    {"symbol":"WMT","companyName":"Walmart Inc.","exchange":"New York Stock Exchange","industry":"Retail - Defensive","website":"http://www.walmart.com","description":"Wal-Mart Stores Inc operates retail stores in various formats under various banners. Its operations comprise of three reportable business segments, Walmart U.S., Walmart International and Sam's Club in three categories retail, wholesale and others.","CEO":"C. Douglas McMillon","issueType":"cs","sector":"Consumer Defensive"}]
